### ISSUE TITLE
Memory settings on created .openerp_serverrc are lower than default Odoo values

### ISSUE THREAD

**Issue by luisg123v** [Vauxoo/maintainer-quality-tools#300]
The file `.openerp_serverc` is created with the following values:
```
limit_memory_soft = 1073741824
limit_memory_hard = 1610612736
```

they're set [here](https://github.com/vauxoo/maintainer-quality-tools/blob/master/travis/test_server.py#L442)). However, default Odoo values are higher, 2048MiB and 2560MiB, respectively ([source](https://github.com/odoo/odoo/blob/7cdfe99d44a6df8c36556bfe6a17f5d9b96a8dd5/odoo/tools/config.py#L290)).

So, if I'm not mistaking, those pre-set values are decreasing default ones, instead of increasing them.

**Comment by luisg123v** [comment]
CC @moylop260  @yaniaular

**Comment by moylop260** [comment]
This issue should be fixed after https://github.com/odoo/odoo/commit/189cc4405cbf4a745989dec6c0b2c41d07e42789

Feel free of re-open it if it is not the case.

**Comment by luisg123v** [comment]
@moylop260  
Could you re-open this, please? This still occurs.

**Comment by moylop260** [comment]
Could you add the steps to reproduce the error, please?
FYI we need to reduce the consume of memory since that the containers are small and used for runbot and raditz...

Maybe we need change the code or increase manually the values if you are sure that you need it

**Comment by luisg123v** [comment]
Fixed on https://github.com/Vauxoo/maintainer-quality-tools/pull/307
