### ISSUE TITLE
ImportError: No module named coverage.cmdline

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/maintainer-quality-tools#57]
At the end of lint tests (`LINT_CHECK=1`) there is an Import error as you can see below:

```bash
$ travis_after_tests_success
Traceback (most recent call last):
  File "/home/travis/maintainer-quality-tools/travis/travis_after_tests_success", line 5, in <module>
    from coverage.cmdline import main as coverage_main
ImportError: No module named coverage.cmdline
```

As an example, this error can be seen at the tail of this [log](https://travis-ci.com/Vauxoo/yoytec/jobs/29123272#L487)

**Comment by moylop260** [comment]
@osvalr 
Thank for issue

Now is fixed.
I saw last builds in travis without problem

Could you check it?
Feel free of re-open this issue.

**Comment by osvalr** [comment]
Hi @moylop260 

Check lint checks out at [travis#97760312](https://travis-ci.org/Vauxoo/addons-vauxoo/builds/97760312) that is still show the error this issue indicates

**Comment by osvalr** [comment]
BTW, I can't get this issue reopened

**Comment by moylop260** [comment]
I saw the build greenfy
